#define PIN_LED_PINK PC13
#define PIN_BUZZER PC5
#define PIN_KEY1 PD2
#define PIN_USART1_RX PA10
#define PIN_USART1_TX PA9
#define PIN_SBUS_RX PA3
#define PIN_RGB PB5
#define PIN_MPU_SDI PB15
#define PIN_MPU_SDO PB14
#define PIN_MPU_SCLK PB13
#define PIN_MPU_NSS PB12

#define PIN_MOTOR1_A PC6
#define PIN_MOTOR1_B PC7
#define PIN_MOTOR2_A PC8
#define PIN_MOTOR2_B PC9
#define PIN_MOTOR3_A PA11
#define PIN_MOTOR3_B PA8
